# CPSC 4970 AI + ML: Module 0

Packages that we will use

In [1]:
import sys
import pandas as pd
import matplotlib
import seaborn as sns
import numpy as np
import scipy as sp
import IPython
import sklearn
import mglearn

print("Python version:", sys.version)
print("pandas version:", pd.__version__)
print("matplotlib version:", matplotlib.__version__)
print("NumPy version:", np.__version__)
print("SciPy version:", sp.__version__)
print("IPython version:", IPython.__version__)
print("scikit-learn version:", sklearn.__version__)
print("mglearn version:", mglearn.__version__)
print("seaborn version:", sns.__version__)

Python version: 3.9.5 (v3.9.5:0a7dcbdb13, May  3 2021, 13:17:02) 
[Clang 6.0 (clang-600.0.57)]
pandas version: 1.3.0
matplotlib version: 3.4.2
NumPy version: 1.21.0
SciPy version: 1.7.0
IPython version: 7.25.0
scikit-learn version: 0.24.2
mglearn version: 0.1.9
seaborn version: 0.11.1


# Creating a vector/matrix in numpy

In [2]:
v = np.array([[1, 2, 3]])
print(v)

w = np.array([[4], [9], [3], [2]])
print(w)

A = np.array([[3, 2], [9, -1], [12, 5]])
print(A)

print(v[0][0])
print(w[1][0])
print(A[2][0])

[[1 2 3]]
[[4]
 [9]
 [3]
 [2]]
[[ 3  2]
 [ 9 -1]
 [12  5]]
1
9
12


# Matrix sums, differences, hadamard product and vector norm

In [3]:
print("A=", A)
B = np.array([[-1, -1], [-2, -2], [-3, - 3]])
print("B=", B)
print("A+B=", A+B)
print("A-B=", A-B)
print("A*B", A*B)
print("norm(v)=", np.linalg.norm(v))
print("norm(A)=", np.linalg.norm(A))

A= [[ 3  2]
 [ 9 -1]
 [12  5]]
B= [[-1 -1]
 [-2 -2]
 [-3 -3]]
A+B= [[ 2  1]
 [ 7 -3]
 [ 9  2]]
A-B= [[ 4  3]
 [11  1]
 [15  8]]
A*B [[ -3  -2]
 [-18   2]
 [-36 -15]]
norm(v)= 3.7416573867739413
norm(A)= 16.24807680927192


# Matrix product

In [4]:
A = np.array([[3, 2], [9, -1], [12, 5]])
C = np.array([[1, 0, -1, 3], [0, 3, 3, 1]])
print(f"{A=}")
print(f"{C=}")
print(f"{A@C=}")
print(f"{B.T=}")
print(f"{A @ B.T=}")
print(f"{B.T @ A=}")

A=array([[ 3,  2],
       [ 9, -1],
       [12,  5]])
C=array([[ 1,  0, -1,  3],
       [ 0,  3,  3,  1]])
A@C=array([[  3,   6,   3,  11],
       [  9,  -3, -12,  26],
       [ 12,  15,   3,  41]])
B.T=array([[-1, -2, -3],
       [-1, -2, -3]])
A @ B.T=array([[ -5, -10, -15],
       [ -8, -16, -24],
       [-17, -34, -51]])
B.T @ A=array([[-57, -15],
       [-57, -15]])


# Identity matrix, inverse of a matrix

In [5]:
A = np.array([[3, 2, 6], [9, -1, 4], [12, 5, -1]])
print(f"{A @ np.eye(3)=}")
print(f"{np.eye(3) @ A=}")
B = np.array([[1, 0, 1], [1, 1, -1], [1, -1, 1]])
Binv = np.linalg.inv(B)
print(f"{Binv=}")
print(f"{B @ Binv=}")

A @ np.eye(3)=array([[ 3.,  2.,  6.],
       [ 9., -1.,  4.],
       [12.,  5., -1.]])
np.eye(3) @ A=array([[ 3.,  2.,  6.],
       [ 9., -1.,  4.],
       [12.,  5., -1.]])
Binv=array([[ 0. ,  0.5,  0.5],
       [ 1. ,  0. , -1. ],
       [ 1. , -0.5, -0.5]])
B @ Binv=array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])
